name: PHP Tests

on:
  push:
    branches: [ "master", "main" , "testing"]
  pull_request:

jobs:
  php-lint:
    name: "phplint"
    runs-on: "${{ matrix.operating-system }}"
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - "ubuntu-22.04"
        php-version:
          - "8.1"
          - "8.2"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP runtime
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          tools: phpcs

      - name: Setup dependencies
        run: composer require -n --no-progress overtrue/phplint

      - name: Lint PHP files
        run: ./vendor/bin/phplint -c .phplint.yml -v

      - name: Run PHP CodeSniffer
        run: phpcs -wps --colors
